
package proyectofinaal;

import javax.swing.JOptionPane;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import org.bson.Document;

/**
 *
 * @author User
 */
public class login extends javax.swing.JFrame {
    
    private Document usuario; // Declara la variable para almacenar el documento del usuario recuperado
    String nombreUsuario = ""; 
    private MongoClient mongoClient;
    private MongoDatabase database;
    private MongoConectar mongoConectar;
    private MongoCerrarConexion mongoCerrarConexion;
    
    
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);

        // Crear una instancia de MongoConectar para establecer la conexión
        mongoConectar = new MongoConectar();
        // Crear una instancia de MongoCerrarConexion para cerrar la conexión al salir
        mongoCerrarConexion = new MongoCerrarConexion(mongoConectar.getMongoClient());
        // Resto del código
        // Inicializar la variable "database" con la base de datos obtenida de mongoConectar
        database = mongoConectar.getDatabase();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jTextFieldUser = new javax.swing.JTextField();
        jButtonSesion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Edwardian Script ITC", 1, 24)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Edwardian Script ITC", 1, 36)); // NOI18N
        jLabel3.setText("Password :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Edwardian Script ITC", 1, 36)); // NOI18N
        jLabel2.setText("Usuario :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        jPassword.setFont(new java.awt.Font("Edwardian Script ITC", 1, 36)); // NOI18N
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 230, 40));

        jTextFieldUser.setFont(new java.awt.Font("Edwardian Script ITC", 1, 36)); // NOI18N
        jTextFieldUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 230, 40));

        jButtonSesion.setFont(new java.awt.Font("Edwardian Script ITC", 1, 36)); // NOI18N
        jButtonSesion.setText("Iniciar Seción");
        jButtonSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSesionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, -1, -1));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Edwardian Script ITC", 1, 36)); // NOI18N
        jLabel1.setText("Registrarse ");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 170, 50));

        jLabelFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Proyecto Final POO\\fondoDomotica.jpeg")); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 550));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Proyecto Final POO\\candado.jpeg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 160, 160));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Proyecto Final POO\\fondoceleste.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, -10, 400, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserActionPerformed
        // TODO add your handling code here:
    String usuario = jTextFieldUser.getText(); // Obtener el texto ingresado en el jTextFieldUser
    
    // Aquí puedes agregar la lógica que deseas realizar con el usuario ingresado
    // Por ejemplo, puedes mostrar un mensaje con el usuario ingresado
    
    JOptionPane.showMessageDialog(this, "Usuario ingresado: " + usuario);
    
    // También puedes utilizar la variable nombreUsuario aquí
    JOptionPane.showMessageDialog(this, "Nombre de usuario guardado: " + nombreUsuario);
    }//GEN-LAST:event_jTextFieldUserActionPerformed

    private void jButtonSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSesionActionPerformed
    nombreUsuario = jTextFieldUser.getText();
        String contraseña = new String(jPassword.getPassword());

        // Accede a la colección de usuarios en MongoDB
        MongoCollection<Document> usuariosCollection = database.getCollection("usuarios");

        // Crea un filtro para buscar el usuario
        Document filtro = new Document("usuario", nombreUsuario);
        Document usuarioEncontrado = usuariosCollection.find(filtro).first();

        if (usuarioEncontrado != null) {
            String contraseñaAlmacenada = usuarioEncontrado.getString("contrasena");

            if (contraseña.equals(contraseñaAlmacenada)) {
                // La contraseña coincide, el inicio de sesión es exitoso
                JOptionPane.showMessageDialog(this, "¡Inicio de sesión exitoso!");
                // Almacena el documento del usuario recuperado en la variable "usuario"
                usuario = usuarioEncontrado;
                // Abrir la interfaz Domiticas:
                Domotica domotica = new Domotica(usuario); // Pasa el documento del usuario a la ventana Domotica
                domotica.setVisible(true);

                // Cerrar la interfaz de login:
                this.dispose();
            } else {
                // La contraseña no coincide, muestra un mensaje de error
                JOptionPane.showMessageDialog(this, "Contraseña incorrecta");
            }
        } else {
            // El usuario no fue encontrado en la base de datos, muestra un mensaje de error
            JOptionPane.showMessageDialog(this, "Usuario no encontrado");
        }
    }//GEN-LAST:event_jButtonSesionActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    char[] password = jPassword.getPassword(); // Obtener la contraseña ingresada como un arreglo de caracteres
    
    // Aquí puedes agregar la lógica que deseas realizar con la contraseña ingresada
    // Por ejemplo, puedes convertir el arreglo de caracteres en una cadena y mostrarla en la consola
    
    String contraseña = new String(password);
    System.out.println("Contraseña ingresada: " + contraseña);
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    // Cerrar la ventana actual
    dispose();

    // Crear una instancia de la ventana anterior (Menu)
    registro menu = new registro();
    
    // Hacer visible el JFrame
    menu.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
